graal: remove static final Logger from  DefaultHttpFactories
see: https://github.com/micronaut-projects/micronaut-starter/pull/1773

```
Error: Classes that should be initialized at run time got initialized during image building:
 org.slf4j.LoggerFactory was unintentionally initialized at build time. To see why org.slf4j.LoggerFactory got initialized use --trace-class-initialization=org.slf4j.LoggerFactory
io.micronaut.http.DefaultHttpFactories was unintentionally initialized at build time. To see why io.micronaut.http.DefaultHttpFactories got initialized use --trace-class-initialization=io.micronaut.http.DefaultHttpFactories
To see how the classes got initialized, use --trace-class-initialization=org.slf4j.LoggerFactory,io.micronaut.http.DefaultHttpFactories```
``
```
asses that should be initialized at run time got initialized during image building:
 io.micronaut.http.DefaultHttpFactories was unintentionally initialized at build time. io.micronaut.http.HttpResponseFactory caused initialization of this class with the following trace:
        at io.micronaut.http.DefaultHttpFactories.<clinit>(DefaultHttpFactories.java:37)
        at io.micronaut.http.HttpResponseFactory.<clinit>(HttpResponseFactory.java:29)

``